title: Hot Sauce
date: 2018/08/06
author: Anonymous
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Cool

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
